---
# Required for PS Core to interact with AppX packages.
# https://devblogs.microsoft.com/powershell/announcing-general-availability-of-the-windows-compatibility-module-1-0-0/.
- name: Install WindowsCompatibility PS module
  community.windows.win_psmodule:
    name: WindowsCompatibility
    state: latest

- name: Install winget
  ansible.windows.win_powershell:
    script: |
      # get latest download url
      $URL = "{{ winget_url }}"
      $URL = (Invoke-WebRequest -Uri $URL).Content | ConvertFrom-Json |
        Select-Object -ExpandProperty "assets" |
        Where-Object "browser_download_url" -Match '.msixbundle' |
        Select-Object -ExpandProperty "browser_download_url"
      # download
      Invoke-WebRequest -Uri $URL -OutFile "Setup.msix" -UseBasicParsing

      # install
      Add-AppxPackage -Path "Setup.msix"

      # delete file
      Remove-Item "Setup.msix"
