---
# Use specified software vars.
- name: Get software variables
  ansible.builtin.include_vars:
    file: ../vars/{{ software }}.yml
    name: target_vars

- name: Install latest
  ansible.builtin.include_role:
    name: install_package
  vars:
    assocations: "{{ target_vars.package_name }}"

- name: Set assocations
  ansible.builtin.include_role:
    name: file_association
  vars:
    assocations: "{{ target_vars.package_assocations }}"
