---
# Installs software and configures a workstation.

- name: Setup workstation
  hosts: workstation
  vars:
    # Workstations are on Windows.
    ansible_shell_type: powershell
  roles:
    - { role: prepare }
    - { role: install_pwsh }
    # Activate Windows.
    - { role: activate_microsoft, product: windows }
    # Install common software without configuring.
    - { role: install_package, packages: ['all'] }
    - { role: install_config, package: firefox }
    - { role: install_config, package: imageglass }
    - { role: install_config, package: vlc }
    - { role: install_config, package: vscode }
    - { role: install_config, package: notepadplusplus }
    - { role: install_office }
    - { role: install_winget }
    # TODO: WSL
    # TODO: VSCode Dev Containers
    # TODO: Terminal
    # TODO: Power settings (wake up devices) and wake on lan
    # TODO: Xbox