---
# Installs software and configures a workstation.

- name: Setup workstation
  hosts: workstation
  vars:
    # Workstations are on Windows.
    ansible_shell_type: powershell
  roles:
    - prepare
    - install_pwsh