---
collections:
  - name: ansible.windows
    source: https://galaxy.ansible.com

  - name: community.windows
    source: https://galaxy.ansible.com

  - name: chocolatey.chocolatey
    source: https://galaxy.ansible.com
